import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ReactQueryProvider } from "./ReactQueryProvider";
import ThemeProvider from "../theme";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ThemeProvider>
    <html lang="en">
      <body className={inter.className} >
      <ReactQueryProvider>
      <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </ReactQueryProvider>

        </body>
    </html>
    </ThemeProvider>
  );
}
